Create model and entities and repositories
Medicine-Managmenet-App/backend pull request #2
Opened 2023-06-13 14:56 UTC by misterrevo

@AleksandraKemona W tym mergu masz encje, repozytorai i v0.0.1 migracje dla aktulanego modelu danych

2023-06-13 15:37 UTC, AleksandraKemona commented on conf/flyway-local.conf
> +flyway.locations=filesystem:db/migration
Ja takiej konfiguracji osobno dla flyway nie robiłam. On sobie wszystko z konfiguracji Hibernate wyciągał. A ta lokacja to z tego co wiem jest domyślna. Ale raczej nie powinien ten plik szkodzić. Jedyne co to trzeba będzie pamietać przy jakichkolwiek zmianach, że trzeba tutaj też je wprowadzić.

2023-06-13 15:39 UTC, AleksandraKemona commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +   period_after_opening INT NOT NULL,
period_after_opening może być nulem,

2023-06-13 16:02 UTC, AleksandraKemona reviewed
Uwagi przekazałam w komentarzach.

2023-06-13 16:02 UTC, AleksandraKemona commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +   period_after_opening INT NOT NULL,
Tak samo dosage

2023-06-13 16:02 UTC, AleksandraKemona commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
Brakuje miejsca, które przechowywałoby powiązanie leku z dozowaniem. Po to tworzyłam osobną klasę PrescribedMedicine. Bo jeden lek może mieć różne dawki i godziny stosowania dla każdego członka rodziny jednocześnie. I trzeba to jakoś powiązać z klasą PrescribedMedicines albo stworzyć osobną tabelę.

2023-06-13 16:02 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/Medicine.java
> +    private OffsetDateTime administrationTime;
Tu mi się gdzieś zawieruszyło przy przyklepywaniu ze swagera, ale to powinna być lista, ponieważ często jest kilka dawek w ciągu doby i wszystkie godziny powinny być wtedy dodane. W DTO już poprawiłam.

2023-06-13 16:02 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/User.java
> +    private String password;
login i password powinny być @NotNull

2023-06-13 16:02 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/Medicine.java
> +    private String name;
name i expiration date powinny być @NotNull

2023-06-13 16:02 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMemberChild.java
> +
Nie wiem czy age i weight nie powinny być @NotNull. Jeśli FamilyMember jest dzieckiem to musi mieć te dane uzupełnione.

2023-06-13 16:02 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMember.java
> +    @OneToOne
name i isChild powinnny być @NotNull

2023-06-13 17:06 UTC, misterrevo commented on conf/flyway-local.conf
> +flyway.locations=filesystem:db/migration
Podlinkujesz cos wiecej o tym flyway, bo moja wiedza opiera sie tylko o baledunga

2023-06-13 17:17 UTC, misterrevo commented on src/main/java/pl/zaprogramujzycie/mma/entity/Medicine.java
> +    private String name;
notnull jest dla walidacji dal baz danych w adnotacji column nullable daje sie na false

2023-06-13 17:18 UTC, misterrevo commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMemberChild.java
> +
Ale jak damy nullable false to nie zapiszemy zwyklego familymember, bo on te kolumny bedzie mial nullowe

2023-06-13 17:20 UTC, misterrevo commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
Masz jakis pomysl jak to rozwiazac?

2023-06-14 09:44 UTC, AleksandraKemona commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
Moim pomysłem była ta dodatkowa klasa, która wiązałaby id leku z dawkowaniem. Chyba, żeby jakoś ogarnąć klasę PrescribedMedicines żeby generowała joined table w której każdemu lekowi z listy przypisywałaby dawkę i godzinę. Ale to chyba wtedy musiałaby mieć dodatkowe pola. Albo listy/tabele które miałyby narzucone identyczne indeksy dla leku, dawki i godzin. I przy pobieraniu funkcja sprawdzająca indeks leku i pobierająca z pozostałych zbiorów dane o tym samym indeksie.

2023-06-14 09:46 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/Medicine.java
> +    private String name;
Ja miałam @NotNull i działało. Może być nullable = false, wszystko mi jedno :)

2023-06-14 09:47 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMemberChild.java
> +
OK. to trzeba przy walidacji formularza zadbać, żeby nie dało nie utworzyć dziecka bez wagi i wieku.

2023-06-15 10:33 UTC, misterrevo commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMemberChild.java
> +
Po stronie be powinnismy to zabezpieczyc, pronouje dodac taka walidacje w dto

2023-06-15 10:34 UTC, misterrevo commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
To zrobie osobna klase i powiaze onetomany z medicament

2023-06-15 10:37 UTC, misterrevo commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
Tylko te dawki nie powinny byc przypisane do konkretnego familymember?

2023-06-15 10:37 UTC, misterrevo commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
Nie lepiej zalozyc sytuacje ze kazdy posiada swoje leki?

2023-06-16 06:58 UTC, AleksandraKemona requested changes

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/MmaApplication.java
> +import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
Nieużywane importy.

2023-06-16 06:58 UTC, AleksandraKemona commented on db/migration/V0_0_1_CREATE_DATABASE_SCHEMA.sql
> +ALTER TABLE family_members ADD CONSTRAINT FK_FAMILY_MEMBERS_ON_PRESCRIBEDMEDICINES FOREIGN KEY (prescribed_medicines_id) REFERENCES prescribed_medicines (id);
nie ma to sensu, ponieważ powinna być wspólna lista leków dla domu a do tego każdy może posiadać inne dawkowanie dla danego leku. Do familyMember przypisujemy zestaw: lek wybrany z listy wszystkich leków + dawka + godziny. Jeśli chcemy ograniczyć klasy to tworząc klasę PrescribedMedicine która ma pola: medicineId, dosage i List OffsetDateTime administrationTime możemy zrezygnować z klasy PrescribedMedicines i tą listę przenieść do FamilyMember jako List PrescribedMedicines

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMemberChild.java
> +
W DTO jest taka walidacja. I to wystarczy?

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMember.java
> -        return isChild == that.isChild && Objects.equals(id, that.id) && Objects.equals(name, that.name) && Objects.equals(prescribedMedicines, that.prescribedMedicines);
Obcięłabym parametry we wszystkich albo w większości generowanych equals. Wydaje mi się, że w większości wystarczy id + np. name lub jedno inne pole, które jest unique

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/FamilyMember.java
> +    private User user;
z tym mapowaniem to jeszcze bym się zastanowiła, bo nie każdy FamilyMember jest Userem. Czy nam się to nie wysypie na nullach?

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/Medicine.java
>      private List<OffsetDateTime> administrationTimes;
Tak jak ustaliliśmy w innym komentarzu: dosage i administrationTimes przenosimy do PrescribedMedicine

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/PrescribedMedicines.java
Tak jak pisałam w innym komentarzu, z tej klasy możemy zrezygnować, podpinamy listę do FamilyMember, a lista zawiera PrescribedMedicines, z którego na front przerzucana jest nazwa pobrana z id podpiętego leku, taka i godzina.

2023-06-16 06:58 UTC, AleksandraKemona commented on src/main/java/pl/zaprogramujzycie/mma/entity/Family.java
Tu jeszcze powinna być lista wszystkich leków rodziny i mamy gotowy model.

2023-06-16 15:28 UTC, AleksandraKemona approved these changes

2023-06-16 15:29 UTC, merged